name: Icon removal
description: Request an icon be removed
title: 'Removal: <name>'

body:
  - type: input
    attributes:
      label: Name
      placeholder: 'Example: Oracle'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reason for Removal
      placeholder: 'Example: Oracle does not allow the use of their icons without explicit approval'
    validations:
      required: true
