name: Lint

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 * * 0"
  workflow_dispatch:

jobs:
  python_lint:
    name: Python Lint

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - name: Check out the codebase
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit flake8 pytest ruff
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        grep -rl '^#!/.*py' | xargs -n1 flake8 --extend-ignore=E501

    - name: Lint with ruff
      run: |
        ruff check . --ignore E501

    - name: Bandit
      run: |
        bandit -r .

  png_search:
    name: PNG Search

    runs-on: ubuntu-latest

    steps:
    - name: Check out the codebase
      uses: actions/checkout@v4

    - name: Search for encoded PNG files
      run: |
        if grep -irlq "png|jpg|jpeg" assets/*.svg; then
          echo 'ERROR: Found PNG information in the assets directory!'
          exit 1
        fi
